<a href="https://colab.research.google.com/github/Sumitsharma12321/Deep-Learning-demo/blob/main/Keras_tuner.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'pima-indians-diabetes-database' dataset.
Path to dataset files: /kaggle/input/pima-indians-diabetes-database

In [4]:
import os

print(os.listdir(path))

['diabetes.csv']

In [5]:
import pandas as pd
import os

file_path = os.path.join(path, "diabetes.csv")
df = pd.read_csv(file_path)

df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [6]:
df.corr()["Outcome"]

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [7]:
x = df.drop("Outcome", axis=1)
y = df["Outcome"]

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [9]:
X = scaler.fit_transform(x)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [11]:
import tensorflow
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

In [12]:
model = Sequential()

model.add(Dense(32, activation="relu", input_dim=8))
model.add(Dense(1, activation="sigmoid"))

model.compile(optimizer="Adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.fit(batch_size=32, x=X_train, y=y_train, epochs=10, validation_data=(X_test, y_test))

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 55ms/step - accuracy: 0.5831 - loss: 0.7092 - val_accuracy: 0.6039 - val_loss: 0.6885
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6482 - loss: 0.6613 - val_accuracy: 0.6494 - val_loss: 0.6483
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6792 - loss: 0.6226 - val_accuracy: 0.6948 - val_loss: 0.6129
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5888 - val_accuracy: 0.7208 - val_loss: 0.5844
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7264 - loss: 0.5608 - val_accuracy: 0.7273 - val_loss: 0.5614
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7345 - loss: 0.5379 - val_accuracy: 0.7338 - val_loss: 0.5441
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7427 - loss: 0.5204 - val_accuracy: 0.7532 - val_loss: 0.5291
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5060 - val_accuracy: 0.7468 - val_loss: 0.5220
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4955 - val_accuracy: 0.7532 - val_loss: 0.5156
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4859 - val_accuracy: 0.7662 - val_loss: 0.5104

In [14]:
# How to select appropriate optimizer
# number of neuron in layer
# how to select no of layer
# All in one model

In [15]:
import keras_tuner as kt

In [16]:
def build_model(hp):

  model = Sequential()
  model.add(Dense(32, activation="relu", input_dim=8))
  model.add(Dense(1, activation="sigmoid"))

  model.compile(optimizer=hp.Choice("optimizer", values=["adam", "sgd", "rmsprop","adadelta"]),
                loss="binary_crossentropy",
                metrics=["accuracy"])

  return model

In [17]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [18]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [19]:
best_hp = tuner.get_best_hyperparameters()[0]

print(best_hp.values)

{'optimizer': 'adam'}

In [20]:
tuner.results_summary()

Results summary
Results in ./untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 0 summary
Hyperparameters:
optimizer: adam
Score: 0.7792207598686218

Trial 3 summary
Hyperparameters:
optimizer: sgd
Score: 0.7077922224998474

Trial 2 summary
Hyperparameters:
optimizer: rmsprop
Score: 0.6948052048683167

Trial 1 summary
Hyperparameters:
optimizer: adadelta
Score: 0.5909090638160706

In [21]:
# you can also extract your model
model = tuner.get_best_models(num_models=1)[0]
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=10,validation_data=(X_test,y_test))

Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 48ms/step - accuracy: 0.7655 - loss: 0.4929 - val_accuracy: 0.7922 - val_loss: 0.5272
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4799 - val_accuracy: 0.7857 - val_loss: 0.5207
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4721 - val_accuracy: 0.7857 - val_loss: 0.5171
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4656 - val_accuracy: 0.7857 - val_loss: 0.5162
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4620 - val_accuracy: 0.7857 - val_loss: 0.5148
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.4580 - val_accuracy: 0.7857 - val_loss: 0.5135
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.4556 - val_accuracy: 0.7857 - val_loss: 0.5123
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7638 - loss: 0.4526 - val_accuracy: 0.7727 - val_loss: 0.5156
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4495 - val_accuracy: 0.7727 - val_loss: 0.5134
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4475 - val_accuracy: 0.7857 - val_loss: 0.5138
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4459 - val_accuracy: 0.7922 - val_loss: 0.5147
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4444 - val_accuracy: 0.7922 - val_loss: 0.5159
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4428 - val_accuracy: 0.7922 - val_loss: 0.5175
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4418 - val_accuracy: 0.7727 - val_loss: 0.5182
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4401 - val_accuracy: 0.7727 - val_loss: 0.5185
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4390 - val_accuracy: 0.7662 - val_loss: 0.5168
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4384 - val_accuracy: 0.7597 - val_loss: 0.5202
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4374 - val_accuracy: 0.7468 - val_loss: 0.5225
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4362 - val_accuracy: 0.7532 - val_loss: 0.5227
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4351 - val_accuracy: 0.7532 - val_loss: 0.5222
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4345 - val_accuracy: 0.7532 - val_loss: 0.5225
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4331 - val_accuracy: 0.7532 - val_loss: 0.5233
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7834 - loss: 0.4328 - val_accuracy: 0.7597 - val_loss: 0.5221
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4317 - val_accuracy: 0.7597 - val_loss: 0.5229
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7785 - loss: 0.4314 - val_accuracy: 0.7597 - val_loss: 0.5221
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4300 - val_accuracy: 0.7597 - val_loss: 0.5232
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4296 - val_accuracy: 0.7597 - val_loss: 0.5219
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4286 - val_accuracy: 0.7597 - val_loss: 0.5228
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4282 - val_accuracy: 0.7597 - val_loss: 0.5237
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7834 - loss: 0.4275 - val_accuracy: 0.7597 - val_loss: 0.5226
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4265 - val_accuracy: 0.7597 - val_loss: 0.5246
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4260 - val_accuracy: 0.7597 - val_loss: 0.5248
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4257 - val_accuracy: 0.7532 - val_loss: 0.5258
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4250 - val_accuracy: 0.7532 - val_loss: 0.5248
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4244 - val_accuracy: 0.7532 - val_loss: 0.5247
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4236 - val_accuracy: 0.7597 - val_loss: 0.5265
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4232 - val_accuracy: 0.7597 - val_loss: 0.5270
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4225 - val_accuracy: 0.7532 - val_loss: 0.5276
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4219 - val_accuracy: 0.7597 - val_loss: 0.5288
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4221 - val_accuracy: 0.7532 - val_loss: 0.5301
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4209 - val_accuracy: 0.7597 - val_loss: 0.5264
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4204 - val_accuracy: 0.7597 - val_loss: 0.5256
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4200 - val_accuracy: 0.7597 - val_loss: 0.5256
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4196 - val_accuracy: 0.7532 - val_loss: 0.5283
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4190 - val_accuracy: 0.7532 - val_loss: 0.5300
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4189 - val_accuracy: 0.7597 - val_loss: 0.5313
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4178 - val_accuracy: 0.7597 - val_loss: 0.5292
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4174 - val_accuracy: 0.7662 - val_loss: 0.5265
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4177 - val_accuracy: 0.7597 - val_loss: 0.5274
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4167 - val_accuracy: 0.7597 - val_loss: 0.5280
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4167 - val_accuracy: 0.7662 - val_loss: 0.5264
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4157 - val_accuracy: 0.7597 - val_loss: 0.5267
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4155 - val_accuracy: 0.7597 - val_loss: 0.5266
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4148 - val_accuracy: 0.7597 - val_loss: 0.5273
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4142 - val_accuracy: 0.7597 - val_loss: 0.5286
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4141 - val_accuracy: 0.7597 - val_loss: 0.5275
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4134 - val_accuracy: 0.7597 - val_loss: 0.5273
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4130 - val_accuracy: 0.7597 - val_loss: 0.5297
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4123 - val_accuracy: 0.7597 - val_loss: 0.5308
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4121 - val_accuracy: 0.7597 - val_loss: 0.5309
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4115 - val_accuracy: 0.7532 - val_loss: 0.5331
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4116 - val_accuracy: 0.7597 - val_loss: 0.5330
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4109 - val_accuracy: 0.7403 - val_loss: 0.5321
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4106 - val_accuracy: 0.7597 - val_loss: 0.5331
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8046 - loss: 0.4102 - val_accuracy: 0.7532 - val_loss: 0.5331
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4099 - val_accuracy: 0.7532 - val_loss: 0.5331
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4092 - val_accuracy: 0.7727 - val_loss: 0.5327
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4090 - val_accuracy: 0.7662 - val_loss: 0.5353
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4090 - val_accuracy: 0.7597 - val_loss: 0.5358
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4081 - val_accuracy: 0.7532 - val_loss: 0.5373
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4082 - val_accuracy: 0.7468 - val_loss: 0.5400
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4074 - val_accuracy: 0.7468 - val_loss: 0.5412
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4079 - val_accuracy: 0.7468 - val_loss: 0.5421
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4062 - val_accuracy: 0.7468 - val_loss: 0.5414
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4058 - val_accuracy: 0.7532 - val_loss: 0.5411
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4055 - val_accuracy: 0.7532 - val_loss: 0.5390
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4050 - val_accuracy: 0.7532 - val_loss: 0.5400
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4046 - val_accuracy: 0.7532 - val_loss: 0.5412
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4045 - val_accuracy: 0.7532 - val_loss: 0.5425
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4045 - val_accuracy: 0.7468 - val_loss: 0.5407
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4039 - val_accuracy: 0.7532 - val_loss: 0.5425
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8078 - loss: 0.4035 - val_accuracy: 0.7532 - val_loss: 0.5418
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8062 - loss: 0.4031 - val_accuracy: 0.7662 - val_loss: 0.5392
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8078 - loss: 0.4021 - val_accuracy: 0.7403 - val_loss: 0.5423
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4023 - val_accuracy: 0.7468 - val_loss: 0.5422
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4019 - val_accuracy: 0.7468 - val_loss: 0.5446
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4019 - val_accuracy: 0.7403 - val_loss: 0.5455
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4012 - val_accuracy: 0.7532 - val_loss: 0.5436
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4008 - val_accuracy: 0.7532 - val_loss: 0.5433
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4001 - val_accuracy: 0.7532 - val_loss: 0.5444

In [23]:
# what is the right number of neuron in this layer?
# Here, we specify the minimum and maximum number of neurons,
# along with the step size

def build_model(hp):

  model = Sequential()

  units=hp.Int("units", min_value=8, max_value=128, step=8)

  model.add(Dense(units=units, activation="relu", input_dim=8))
  model.add(Dense(1, activation="sigmoid"))

  model.compile(optimizer="Adam",
                loss="binary_crossentropy",
                metrics=["accuracy"])

  return model

In [24]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir')

In [25]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6363636255264282

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 20s

In [26]:
best_hp = tuner.get_best_hyperparameters()[0]

print(best_hp.values)

{'units': 48}

In [27]:
tuner.results_summary()

Results summary
Results in mydir/untitled_project
Showing 10 best trials
Objective(name="val_accuracy", direction="max")

Trial 3 summary
Hyperparameters:
units: 48
Score: 0.7727272510528564

Trial 1 summary
Hyperparameters:
units: 96
Score: 0.7467532753944397

Trial 0 summary
Hyperparameters:
units: 120
Score: 0.7402597665786743

Trial 2 summary
Hyperparameters:
units: 32
Score: 0.7207792401313782

Trial 4 summary
Hyperparameters:
units: 8
Score: 0.6363636255264282

In [28]:
model= tuner.get_best_models(num_models=1)[0]
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 48)             │           432 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            49 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 481 (1.88 KB)

 Trainable params: 481 (1.88 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=10,validation_data=(X_test,y_test))

Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 49ms/step - accuracy: 0.7655 - loss: 0.4983 - val_accuracy: 0.7792 - val_loss: 0.4962
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7687 - loss: 0.4838 - val_accuracy: 0.7857 - val_loss: 0.4897
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4745 - val_accuracy: 0.7792 - val_loss: 0.4867
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4675 - val_accuracy: 0.7857 - val_loss: 0.4843
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7736 - loss: 0.4618 - val_accuracy: 0.7792 - val_loss: 0.4842
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4582 - val_accuracy: 0.7792 - val_loss: 0.4837
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4542 - val_accuracy: 0.7662 - val_loss: 0.4856
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4516 - val_accuracy: 0.7727 - val_loss: 0.4869
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4494 - val_accuracy: 0.7727 - val_loss: 0.4886
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4477 - val_accuracy: 0.7662 - val_loss: 0.4908
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4454 - val_accuracy: 0.7662 - val_loss: 0.4916
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4438 - val_accuracy: 0.7662 - val_loss: 0.4927
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4419 - val_accuracy: 0.7662 - val_loss: 0.4962
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4403 - val_accuracy: 0.7597 - val_loss: 0.4986
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4390 - val_accuracy: 0.7662 - val_loss: 0.4989
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4375 - val_accuracy: 0.7662 - val_loss: 0.4992
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4357 - val_accuracy: 0.7597 - val_loss: 0.5006
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7915 - loss: 0.4346 - val_accuracy: 0.7662 - val_loss: 0.5027
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4342 - val_accuracy: 0.7597 - val_loss: 0.5037
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7932 - loss: 0.4327 - val_accuracy: 0.7597 - val_loss: 0.5039
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7915 - loss: 0.4322 - val_accuracy: 0.7597 - val_loss: 0.5034
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4311 - val_accuracy: 0.7597 - val_loss: 0.5050
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4298 - val_accuracy: 0.7597 - val_loss: 0.5061
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4287 - val_accuracy: 0.7597 - val_loss: 0.5068
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7899 - loss: 0.4282 - val_accuracy: 0.7532 - val_loss: 0.5087
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4267 - val_accuracy: 0.7597 - val_loss: 0.5082
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4257 - val_accuracy: 0.7597 - val_loss: 0.5070
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7932 - loss: 0.4251 - val_accuracy: 0.7597 - val_loss: 0.5104
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4247 - val_accuracy: 0.7662 - val_loss: 0.5084
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4229 - val_accuracy: 0.7532 - val_loss: 0.5099
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4218 - val_accuracy: 0.7532 - val_loss: 0.5110
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4210 - val_accuracy: 0.7597 - val_loss: 0.5107
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4207 - val_accuracy: 0.7597 - val_loss: 0.5105
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4198 - val_accuracy: 0.7532 - val_loss: 0.5122
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4191 - val_accuracy: 0.7532 - val_loss: 0.5126
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4184 - val_accuracy: 0.7532 - val_loss: 0.5149
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4173 - val_accuracy: 0.7532 - val_loss: 0.5141
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4166 - val_accuracy: 0.7468 - val_loss: 0.5167
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4159 - val_accuracy: 0.7532 - val_loss: 0.5175
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4153 - val_accuracy: 0.7532 - val_loss: 0.5173
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4146 - val_accuracy: 0.7532 - val_loss: 0.5161
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4137 - val_accuracy: 0.7532 - val_loss: 0.5177
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4140 - val_accuracy: 0.7532 - val_loss: 0.5191
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4132 - val_accuracy: 0.7532 - val_loss: 0.5215
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4122 - val_accuracy: 0.7597 - val_loss: 0.5162
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4113 - val_accuracy: 0.7597 - val_loss: 0.5190
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4113 - val_accuracy: 0.7532 - val_loss: 0.5222
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4102 - val_accuracy: 0.7338 - val_loss: 0.5249
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4097 - val_accuracy: 0.7403 - val_loss: 0.5240
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4089 - val_accuracy: 0.7597 - val_loss: 0.5178
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4076 - val_accuracy: 0.7597 - val_loss: 0.5174
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4072 - val_accuracy: 0.7597 - val_loss: 0.5197
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8013 - loss: 0.4069 - val_accuracy: 0.7597 - val_loss: 0.5183
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8029 - loss: 0.4063 - val_accuracy: 0.7597 - val_loss: 0.5205
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4060 - val_accuracy: 0.7597 - val_loss: 0.5199
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8127 - loss: 0.4050 - val_accuracy: 0.7597 - val_loss: 0.5206
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4046 - val_accuracy: 0.7597 - val_loss: 0.5211
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4040 - val_accuracy: 0.7597 - val_loss: 0.5221
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8046 - loss: 0.4029 - val_accuracy: 0.7597 - val_loss: 0.5223
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4030 - val_accuracy: 0.7597 - val_loss: 0.5226
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4025 - val_accuracy: 0.7597 - val_loss: 0.5226
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.4017 - val_accuracy: 0.7597 - val_loss: 0.5230
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.4009 - val_accuracy: 0.7532 - val_loss: 0.5223
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4013 - val_accuracy: 0.7532 - val_loss: 0.5200
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.4004 - val_accuracy: 0.7532 - val_loss: 0.5213
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8078 - loss: 0.3999 - val_accuracy: 0.7597 - val_loss: 0.5267
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.3999 - val_accuracy: 0.7597 - val_loss: 0.5253
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8094 - loss: 0.3996 - val_accuracy: 0.7532 - val_loss: 0.5259
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8111 - loss: 0.3985 - val_accuracy: 0.7468 - val_loss: 0.5268
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3981 - val_accuracy: 0.7468 - val_loss: 0.5266
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.3974 - val_accuracy: 0.7468 - val_loss: 0.5267
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3965 - val_accuracy: 0.7532 - val_loss: 0.5276
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.3963 - val_accuracy: 0.7532 - val_loss: 0.5246
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8160 - loss: 0.3964 - val_accuracy: 0.7532 - val_loss: 0.5258
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3954 - val_accuracy: 0.7532 - val_loss: 0.5266
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3954 - val_accuracy: 0.7468 - val_loss: 0.5278
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8176 - loss: 0.3946 - val_accuracy: 0.7468 - val_loss: 0.5274
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3956 - val_accuracy: 0.7403 - val_loss: 0.5253
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3942 - val_accuracy: 0.7403 - val_loss: 0.5263
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3941 - val_accuracy: 0.7468 - val_loss: 0.5324
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3931 - val_accuracy: 0.7468 - val_loss: 0.5309
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3929 - val_accuracy: 0.7468 - val_loss: 0.5301
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8208 - loss: 0.3915 - val_accuracy: 0.7403 - val_loss: 0.5337
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3919 - val_accuracy: 0.7403 - val_loss: 0.5331
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8192 - loss: 0.3919 - val_accuracy: 0.7403 - val_loss: 0.5345
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3909 - val_accuracy: 0.7403 - val_loss: 0.5348
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8306 - loss: 0.3902 - val_accuracy: 0.7468 - val_loss: 0.5353
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3897 - val_accuracy: 0.7403 - val_loss: 0.5358
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8225 - loss: 0.3899 - val_accuracy: 0.7403 - val_loss: 0.5368
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8241 - loss: 0.3903 - val_accuracy: 0.7403 - val_loss: 0.5377

here we can also find neuron on every layer

In [30]:
# How to select number of layers?
def build_model(hp):

  model = Sequential()
  model.add(Dense(72, activation="relu", input_dim=8))

  for i in range(hp.Int("num_layers", min_value=1, max_value=10)):

    model.add(Dense(units=hp.Int("units_" + str(i), min_value=32, max_value=512, step=32), activation="relu"))

  model.add(Dense(1, activation="sigmoid"))

  model.compile(optimizer="Adam",
                loss="binary_crossentropy",
                metrics=["accuracy"])

  return model

In [31]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=5,
                        directory='mydir',
                        project_name='num_layers')

In [32]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 07s]
val_accuracy: 0.7727272510528564

Best val_accuracy So Far: 0.7792207598686218
Total elapsed time: 00h 00m 35s

In [33]:
best_hp = tuner.get_best_hyperparameters()[0]

print(best_hp.values)

{'num_layers': 4, 'units_0': 192, 'units_1': 416, 'units_2': 192, 'units_3': 128, 'units_4': 448, 'units_5': 224, 'units_6': 64, 'units_7': 416, 'units_8': 512, 'units_9': 32}

In [34]:
model = tuner.get_best_models(num_models=1)[0]
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 26 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 72)             │           648 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 192)            │        14,016 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 416)            │        80,288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 192)            │        80,064 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │        24,704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 199,849 (780.66 KB)

 Trainable params: 199,849 (780.66 KB)

 Non-trainable params: 0 (0.00 B)

In [35]:
model.fit(X_train,y_train,batch_size=32,epochs=25,initial_epoch=10,validation_data=(X_test,y_test))

Epoch 11/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 5s 90ms/step - accuracy: 0.7850 - loss: 0.4466 - val_accuracy: 0.7532 - val_loss: 0.5505
Epoch 12/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8094 - loss: 0.4110 - val_accuracy: 0.7273 - val_loss: 0.5543
Epoch 13/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8062 - loss: 0.4151 - val_accuracy: 0.7468 - val_loss: 0.5576
Epoch 14/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.3905 - val_accuracy: 0.7727 - val_loss: 0.5409
Epoch 15/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8274 - loss: 0.3803 - val_accuracy: 0.7468 - val_loss: 0.5459
Epoch 16/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8176 - loss: 0.3665 - val_accuracy: 0.7662 - val_loss: 0.5368
Epoch 17/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8453 - loss: 0.3424 - val_accuracy: 0.7597 - val_loss: 0.6273
Epoch 18/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3420 - val_accuracy: 0.7143 - val_loss: 0.7191
Epoch 19/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8550 - loss: 0.3106 - val_accuracy: 0.7338 - val_loss: 0.6073
Epoch 20/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8827 - loss: 0.3011 - val_accuracy: 0.6948 - val_loss: 0.7232
Epoch 21/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8648 - loss: 0.2930 - val_accuracy: 0.7143 - val_loss: 0.7247
Epoch 22/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8779 - loss: 0.2671 - val_accuracy: 0.7403 - val_loss: 0.6412
Epoch 23/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8762 - loss: 0.2675 - val_accuracy: 0.7078 - val_loss: 0.7868
Epoch 24/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9088 - loss: 0.2237 - val_accuracy: 0.6883 - val_loss: 0.8058
Epoch 25/25
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2487 - val_accuracy: 0.7273 - val_loss: 0.8008

In [36]:
def build_model(hp):

  model = Sequential()

  counter = 0

  for i in range(hp.Int("num_layers", min_value=1, max_value=10)):

    if counter == 0:

      model.add(
          Dense(
              units=hp.Int("units" + str(i), min_value=8, max_value=128, step=8),
              activation=hp.Choice("activation" + str(i), values=["relu","tanh", "sigmoid"]),
              input_dim=8
          )
      )
      model.add(
          Dropout(
              hp.Choice("dropout" + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5,0.6,0.7,0.8,0.9])
          )
      )
    else:

      model.add(
          Dense(
              units=hp.Int("units" + str(i), min_value=8, max_value=128, step=8),
              activation=hp.Choice("activation" + str(i), values=["relu","tanh","sigmoid"])
          )
      )
      model.add(
          Dropout(
              hp.Choice("dropout" + str(i), values=[0.1, 0.2, 0.3, 0.4, 0.5,0.6,0.7,0.8,0.9])
          )
      )

    counter += 1

  model.add(Dense(1,activation="sigmoid"))

  model.compile(optimizer=hp.Choice("optimizer", values=["adam", "sgd", "rmsprop","adadelta","nadam"]),
                loss="binary_crossentropy",
                metrics=["accuracy"])

  return model

In [37]:
import shutil

shutil.rmtree('mydir', ignore_errors=True)

In [38]:
for hp in tuner.oracle.hyperparameters.space:
    print(hp.name)

num_layers
units_0
units_1
units_2
units_3
units_4
units_5
units_6
units_7
units_8
units_9

In [39]:
tuner = kt.RandomSearch(build_model,
                        objective='val_accuracy',
                        max_trials=20,
                        directory='mydir',
                        project_name='final')

In [40]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 20 Complete [00h 00m 12s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.7142857313156128
Total elapsed time: 00h 04m 01s

In [41]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 5,
 'units0': 88,
 'activation0': 'tanh',
 'dropout0': 0.3,
 'optimizer': 'adam',
 'units1': 48,
 'activation1': 'tanh',
 'dropout1': 0.3,
 'units2': 112,
 'activation2': 'relu',
 'dropout2': 0.5,
 'units3': 48,
 'activation3': 'sigmoid',
 'dropout3': 0.4,
 'units4': 128,
 'activation4': 'relu',
 'dropout4': 0.7,
 'units5': 56,
 'activation5': 'tanh',
 'dropout5': 0.2,
 'units6': 112,
 'activation6': 'relu',
 'dropout6': 0.6,
 'units7': 80,
 'activation7': 'tanh',
 'dropout7': 0.9,
 'units8': 80,
 'activation8': 'relu',
 'dropout8': 0.8,
 'units9': 24,
 'activation9': 'sigmoid',
 'dropout9': 0.5}

In [42]:
best_hp = tuner.get_best_hyperparameters()[0]

for k, v in best_hp.values.items():
    print(k, ":", v)

num_layers : 5
units0 : 88
activation0 : tanh
dropout0 : 0.3
optimizer : adam
units1 : 48
activation1 : tanh
dropout1 : 0.3
units2 : 112
activation2 : relu
dropout2 : 0.5
units3 : 48
activation3 : sigmoid
dropout3 : 0.4
units4 : 128
activation4 : relu
dropout4 : 0.7
units5 : 56
activation5 : tanh
dropout5 : 0.2
units6 : 112
activation6 : relu
dropout6 : 0.6
units7 : 80
activation7 : tanh
dropout7 : 0.9
units8 : 80
activation8 : relu
dropout8 : 0.8
units9 : 24
activation9 : sigmoid
dropout9 : 0.5

In [43]:
model = tuner.get_best_models(num_models=1)[0]
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 88)             │           792 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 88)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 48)             │         4,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 48)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 112)            │         5,488 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 112)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 48)             │         5,424 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 48)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 128)            │         6,272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 128)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │           129 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 22,377 (87.41 KB)

 Trainable params: 22,377 (87.41 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
model.fit(X_train,y_train,epochs=100,initial_epoch=10,validation_data=(X_test,y_test))

Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 8s 187ms/step - accuracy: 0.6954 - loss: 0.5843 - val_accuracy: 0.7143 - val_loss: 0.5309
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7215 - loss: 0.5348 - val_accuracy: 0.7078 - val_loss: 0.5221
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7378 - loss: 0.5272 - val_accuracy: 0.7078 - val_loss: 0.5222
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7524 - loss: 0.5185 - val_accuracy: 0.7013 - val_loss: 0.5229
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7427 - loss: 0.5095 - val_accuracy: 0.7143 - val_loss: 0.5232
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5206 - val_accuracy: 0.7078 - val_loss: 0.5246
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7459 - loss: 0.5062 - val_accuracy: 0.6948 - val_loss: 0.5303
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7476 - loss: 0.4915 - val_accuracy: 0.7078 - val_loss: 0.5276
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7557 - loss: 0.5090 - val_accuracy: 0.7143 - val_loss: 0.5283
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7622 - loss: 0.4908 - val_accuracy: 0.7273 - val_loss: 0.5250
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7541 - loss: 0.4964 - val_accuracy: 0.7273 - val_loss: 0.5245
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7655 - loss: 0.4996 - val_accuracy: 0.7403 - val_loss: 0.5235
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7671 - loss: 0.5014 - val_accuracy: 0.7532 - val_loss: 0.5181
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7622 - loss: 0.4840 - val_accuracy: 0.7532 - val_loss: 0.5189
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7736 - loss: 0.4742 - val_accuracy: 0.7597 - val_loss: 0.5147
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7736 - loss: 0.4864 - val_accuracy: 0.7597 - val_loss: 0.5117
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4874 - val_accuracy: 0.7338 - val_loss: 0.5216
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4731 - val_accuracy: 0.7338 - val_loss: 0.5241
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4834 - val_accuracy: 0.7403 - val_loss: 0.5245
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4797 - val_accuracy: 0.7468 - val_loss: 0.5232
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7671 - loss: 0.4818 - val_accuracy: 0.7338 - val_loss: 0.5294
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4800 - val_accuracy: 0.7468 - val_loss: 0.5316
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4753 - val_accuracy: 0.7532 - val_loss: 0.5242
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7590 - loss: 0.4714 - val_accuracy: 0.7597 - val_loss: 0.5279
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4797 - val_accuracy: 0.7273 - val_loss: 0.5329
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7573 - loss: 0.4941 - val_accuracy: 0.7273 - val_loss: 0.5325
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4585 - val_accuracy: 0.7403 - val_loss: 0.5285
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4733 - val_accuracy: 0.7532 - val_loss: 0.5276
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4698 - val_accuracy: 0.7532 - val_loss: 0.5331
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4511 - val_accuracy: 0.7662 - val_loss: 0.5285
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4865 - val_accuracy: 0.7662 - val_loss: 0.5162
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4668 - val_accuracy: 0.7662 - val_loss: 0.5132
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4728 - val_accuracy: 0.7597 - val_loss: 0.5100
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4706 - val_accuracy: 0.7792 - val_loss: 0.5071
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4733 - val_accuracy: 0.7727 - val_loss: 0.5086
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4765 - val_accuracy: 0.7727 - val_loss: 0.5047
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4606 - val_accuracy: 0.7727 - val_loss: 0.5098
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4611 - val_accuracy: 0.7662 - val_loss: 0.5141
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7704 - loss: 0.4681 - val_accuracy: 0.7857 - val_loss: 0.5126
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.4592 - val_accuracy: 0.7857 - val_loss: 0.5061
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4612 - val_accuracy: 0.7792 - val_loss: 0.5052
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7752 - loss: 0.4602 - val_accuracy: 0.7727 - val_loss: 0.5068
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4706 - val_accuracy: 0.7662 - val_loss: 0.5028
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4526 - val_accuracy: 0.7597 - val_loss: 0.5094
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7720 - loss: 0.4646 - val_accuracy: 0.7662 - val_loss: 0.5116
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4706 - val_accuracy: 0.7597 - val_loss: 0.5100
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4514 - val_accuracy: 0.7532 - val_loss: 0.5169
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4731 - val_accuracy: 0.7532 - val_loss: 0.5141
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4657 - val_accuracy: 0.7532 - val_loss: 0.5154
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4687 - val_accuracy: 0.7532 - val_loss: 0.5121
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7736 - loss: 0.4513 - val_accuracy: 0.7597 - val_loss: 0.5102
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7655 - loss: 0.4557 - val_accuracy: 0.7532 - val_loss: 0.5102
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4512 - val_accuracy: 0.7468 - val_loss: 0.5143
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4475 - val_accuracy: 0.7468 - val_loss: 0.5188
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7899 - loss: 0.4700 - val_accuracy: 0.7468 - val_loss: 0.5116
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7638 - loss: 0.4648 - val_accuracy: 0.7532 - val_loss: 0.5038
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4683 - val_accuracy: 0.7532 - val_loss: 0.5093
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7785 - loss: 0.4522 - val_accuracy: 0.7468 - val_loss: 0.5103
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7785 - loss: 0.4768 - val_accuracy: 0.7468 - val_loss: 0.5065
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4592 - val_accuracy: 0.7597 - val_loss: 0.5050
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4564 - val_accuracy: 0.7468 - val_loss: 0.4990
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4660 - val_accuracy: 0.7597 - val_loss: 0.5025
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4587 - val_accuracy: 0.7468 - val_loss: 0.5030
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4563 - val_accuracy: 0.7468 - val_loss: 0.5041
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7997 - loss: 0.4596 - val_accuracy: 0.7468 - val_loss: 0.5082
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4586 - val_accuracy: 0.7597 - val_loss: 0.4955
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7769 - loss: 0.4639 - val_accuracy: 0.7532 - val_loss: 0.4964
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7752 - loss: 0.4513 - val_accuracy: 0.7597 - val_loss: 0.4956
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4355 - val_accuracy: 0.7662 - val_loss: 0.4974
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4418 - val_accuracy: 0.7662 - val_loss: 0.5021
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7687 - loss: 0.4499 - val_accuracy: 0.7662 - val_loss: 0.5066
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7866 - loss: 0.4384 - val_accuracy: 0.7597 - val_loss: 0.5081
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4318 - val_accuracy: 0.7532 - val_loss: 0.5104
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7834 - loss: 0.4419 - val_accuracy: 0.7532 - val_loss: 0.5099
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4322 - val_accuracy: 0.7338 - val_loss: 0.5106
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4459 - val_accuracy: 0.7468 - val_loss: 0.5085
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4551 - val_accuracy: 0.7532 - val_loss: 0.5071
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7997 - loss: 0.4542 - val_accuracy: 0.7662 - val_loss: 0.5020
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7932 - loss: 0.4398 - val_accuracy: 0.7468 - val_loss: 0.5041
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8029 - loss: 0.4525 - val_accuracy: 0.7727 - val_loss: 0.4965
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4620 - val_accuracy: 0.7727 - val_loss: 0.5002
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7948 - loss: 0.4565 - val_accuracy: 0.7532 - val_loss: 0.5024
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8029 - loss: 0.4297 - val_accuracy: 0.7597 - val_loss: 0.5043
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7980 - loss: 0.4506 - val_accuracy: 0.7597 - val_loss: 0.5043
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4403 - val_accuracy: 0.7532 - val_loss: 0.5131
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7948 - loss: 0.4344 - val_accuracy: 0.7532 - val_loss: 0.5154
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7964 - loss: 0.4247 - val_accuracy: 0.7468 - val_loss: 0.5252
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8013 - loss: 0.4457 - val_accuracy: 0.7273 - val_loss: 0.5177
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7980 - loss: 0.4237 - val_accuracy: 0.7468 - val_loss: 0.5123
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.4285 - val_accuracy: 0.7403 - val_loss: 0.5204

In [45]:
best_hp = tuner.get_best_hyperparameters()[0]

for k, v in best_hp.values.items():
    print(k, ":", v)

num_layers : 5
units0 : 88
activation0 : tanh
dropout0 : 0.3
optimizer : adam
units1 : 48
activation1 : tanh
dropout1 : 0.3
units2 : 112
activation2 : relu
dropout2 : 0.5
units3 : 48
activation3 : sigmoid
dropout3 : 0.4
units4 : 128
activation4 : relu
dropout4 : 0.7
units5 : 56
activation5 : tanh
dropout5 : 0.2
units6 : 112
activation6 : relu
dropout6 : 0.6
units7 : 80
activation7 : tanh
dropout7 : 0.9
units8 : 80
activation8 : relu
dropout8 : 0.8
units9 : 24
activation9 : sigmoid
dropout9 : 0.5